name: picar_remote
description: Minimal PiCar controller
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.0.4
  http: ^1.2.0

flutter:
  uses-material-design: true
